import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  GeneratedPack,
  OrientationPackMeta,
  OrientationSignals,
} from "../schema/pack.js";
import { PACK_PATHS, PACK_VERSION } from "../schema/pack.js";

function onlyExisting(root: string, paths: string[]): string[] {
  return paths.filter((p) => p === "." || existsSync(join(root, p)));
}

function cmdTable(commands: OrientationSignals["commands"]): string {
  const rows = Object.entries(commands).filter(([, v]) => Boolean(v));
  if (rows.length === 0) {
    return "_No standard commands detected — confirm in README/CI._";
  }
  return [
    "| Step | Command |",
    "| --- | --- |",
    ...rows.map(([k, v]) => `| ${k} | \`${v}\` |`),
  ].join("\n");
}

export function renderAgentsMd(signals: OrientationSignals): string {
  const title = signals.name ?? "this repository";
  const desc = signals.description?.trim() || "Open-source project (see README).";
  const langs = Object.entries(signals.languages)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([l, n]) => `${l} (${n})`)
    .join(", ");

  const modules = signals.modules
    .map((m) => {
      const reads = onlyExisting(signals.root, m.readWhenTouching)
        .map((p) => `\`${p}\``)
        .join(", ");
      return `- \`${m.path}/\` — ${m.role}${reads ? ` (also read: ${reads})` : ""}`;
    })
    .join("\n");

  const ci =
    signals.ciWorkflows.length === 0
      ? "_No GitHub Actions workflows detected._"
      : signals.ciWorkflows
          .map(
            (w) =>
              `- [\`${w.path}\`](${w.path})${w.name ? ` — ${w.name}` : ""}${
                w.jobs.length ? ` (jobs: ${w.jobs.join(", ")})` : ""
              }`,
          )
          .join("\n");

  return `# AGENTS.md

> Generated by [claude-for-oss](https://github.com/claude-for-oss/claude-for-oss). Paths below were verified to exist at generation time. Prefer this file over guessing.

## Purpose

**${title}** — ${desc}

## Stack

- Primary language: **${signals.primaryLanguage ?? "unknown"}**
- Languages (file counts): ${langs || "n/a"}
- Package manager: **${signals.packageManager ?? "unknown"}**

## Agent workflow commands

${cmdTable(signals.commands)}

## Where to look

${modules || "- Start at repo root and README.md"}

## Architecture map

See [\`docs/agent/architecture.md\`](docs/agent/architecture.md) and [\`docs/agent/blast-radius.md\`](docs/agent/blast-radius.md).

## CI

${ci}

## Conventions

- Keep changes minimal and scoped to the task.
- Run the test command above before opening a PR when possible.
- Cite real file paths; do not invent modules.
- For first agent-friendly issues, see [\`.github/GOOD_FIRST_AGENT.md\`](.github/GOOD_FIRST_AGENT.md).

## Skills

- \`/orient\` — re-read orientation pack
- \`/find-test\` — locate how to run tests

## Spec

Pack format: [\`docs/agent/PACK_SPEC.md\`](docs/agent/PACK_SPEC.md)

---
_Pack structure hash: \`${signals.structureHash}\`_
`;
}

export function renderArchitecture(signals: OrientationSignals): string {
  const dirs = signals.topLevelDirs
    .map((d) => {
      const mod = signals.modules.find((m) => m.path === d);
      return `| \`${d}/\` | ${mod?.role ?? "top-level directory"} |`;
    })
    .join("\n");

  const notable = signals.notableFiles
    .map((f) => `- [\`${f}\`](../../${f})`)
    .join("\n");

  return `# Architecture map (agent)

Generated for agents exploring this repo. Only lists paths that existed when the pack was built.

## Top-level layout

| Path | Role |
| --- | --- |
${dirs || "| `.` | project root |"}

## Notable files

${notable || "_None detected._"}

## Touch guide

${
  signals.modules
    .map((m) => {
      const reads = onlyExisting(signals.root, m.readWhenTouching)
        .map((p) => `\`${p}\``)
        .join(", ");
      return `### \`${m.path}\`\n\nRole: ${m.role}\n\nWhen editing here, also read: ${reads || "n/a"}`;
    })
    .join("\n\n") || "_No module heuristics matched — start from README._"
}

## README excerpt

\`\`\`
${(signals.readmeExcerpt ?? "").slice(0, 1500) || "(no README.md)"}
\`\`\`
`;
}

export function renderBlastRadius(signals: OrientationSignals): string {
  const edges =
    signals.blastEdges.length === 0
      ? "_No static edges inferred. Re-run \`cfo refresh\` after adding package manifests or tests._"
      : [
          "| From | To | Via |",
          "| --- | --- | --- |",
          ...signals.blastEdges.map(
            (e) =>
              `| \`${e.from}\` | \`${e.to}\` | ${e.via ?? "related"} |`,
          ),
        ].join("\n");

  return `# Blast radius hints (best-effort)

Static, heuristic dependency hints for agents. **Not** a full call graph — verify before large refactors.

${edges}

## Rules of thumb

1. Changing CI workflows (\`.github/workflows\`) may affect every package's required checks.
2. Changing root manifests (\`package.json\`, \`Cargo.toml\`, \`go.mod\`) can invalidate install/build assumptions in AGENTS.md — run \`cfo refresh\`.
3. Prefer tests closest to the module you edit.
`;
}

export function renderGoodFirstAgent(signals: OrientationSignals): string {
  const testCmd = signals.commands.test ?? "(document how to test)";
  return `# Good first agent issue template

Use this template when filing issues intended for AI coding agents **and** human newcomers.

## Title

\`[good-first-agent] <short outcome>\`

## Goal

One concrete, verifiable outcome (e.g. "Fix typo in README install section", "Add unit test for X").

## Acceptance criteria

- [ ] Behavior or docs match the goal
- [ ] Tests pass: \`${testCmd}\`
- [ ] Diff stays scoped (avoid drive-by refactors)

## Suggested starting points

${signals.modules
  .slice(0, 5)
  .map((m) => `- \`${m.path}/\` (${m.role})`)
  .join("\n") || "- README.md"}

## Out of scope

- Dependency major upgrades
- Unrelated formatting of the whole tree
- New features without a linked design note

## References

- Orientation: \`AGENTS.md\`
- Architecture: \`docs/agent/architecture.md\`
`;
}

export function renderSkillOrient(): string {
  return `---
name: orient
description: Re-read this repository's Claude-for-OSS orientation pack before exploring or editing.
---

# Orient

1. Read \`AGENTS.md\` (or \`CLAUDE.md\` if present).
2. Read \`docs/agent/architecture.md\` and \`docs/agent/blast-radius.md\`.
3. Confirm install/test commands from the pack before running shell tools.
4. Do not invent paths — only use paths listed in the pack or verified with glob/read.
`;
}

export function renderSkillFindTest(signals: OrientationSignals): string {
  const test = signals.commands.test ?? "see package scripts / Makefile / CI";
  return `---
name: find-test
description: Locate how to run tests in this repository using the orientation pack.
---

# Find test command

1. Prefer the test command from \`AGENTS.md\`: \`${test}\`
2. If missing, check CI workflows under \`.github/workflows/\`.
3. Run the smallest relevant test target for the files you changed.
`;
}

export function generatePack(
  signals: OrientationSignals,
  options: { writeClaudeMd?: boolean } = {},
): GeneratedPack {
  const writeClaudeMd = options.writeClaudeMd ?? true;
  const meta: OrientationPackMeta = {
    packVersion: PACK_VERSION,
    generatedAt: new Date().toISOString(),
    generator: "claude-for-oss@0.1.0",
    structureHash: signals.structureHash,
    root: signals.root,
    primaryLanguage: signals.primaryLanguage,
    packageManager: signals.packageManager,
    commands: signals.commands,
    topLevelDirs: signals.topLevelDirs,
    ciWorkflows: signals.ciWorkflows.map((w) => w.path),
  };

  const agents = renderAgentsMd(signals);
  const files: GeneratedPack["files"] = [
    { relativePath: PACK_PATHS.agents, content: agents },
    {
      relativePath: PACK_PATHS.architecture,
      content: renderArchitecture(signals),
    },
    {
      relativePath: PACK_PATHS.blastRadius,
      content: renderBlastRadius(signals),
    },
    {
      relativePath: PACK_PATHS.goodFirstAgent,
      content: renderGoodFirstAgent(signals),
    },
    {
      relativePath: PACK_PATHS.meta,
      content: JSON.stringify(meta, null, 2) + "\n",
    },
    { relativePath: PACK_PATHS.skillOrient, content: renderSkillOrient() },
    {
      relativePath: PACK_PATHS.skillFindTest,
      content: renderSkillFindTest(signals),
    },
  ];

  if (writeClaudeMd) {
    files.push({
      relativePath: PACK_PATHS.claude,
      content:
        `# CLAUDE.md\n\n` +
        `This repository uses the Claude-for-OSS orientation pack.\n\n` +
        `Follow [\`AGENTS.md\`](AGENTS.md) and [\`docs/agent/\`](docs/agent/) for stack, commands, and architecture.\n`,
    });
  }

  return { meta, files };
}
